package com.obitoboost.app.util

import android.content.Context
import android.content.Intent
import android.graphics.*
import android.net.Uri
import androidx.core.content.FileProvider
import com.obitoboost.app.data.model.BenchmarkComparison
import com.obitoboost.app.data.model.DeviceInfo
import com.obitoboost.app.data.model.GamingProfileType
import java.io.File
import java.io.FileOutputStream

/**
 * Draws the "Export Result" gaming card described in the spec (device,
 * profile, FPS benchmark, before/after, OBITO BOOST branding + watermark)
 * and hands it to Android's native share sheet so it can go to YouTube,
 * TikTok, Instagram, WhatsApp, etc.
 */
object ExportManager {

    private const val W = 1080
    private const val H = 1350

    fun generateResultCard(
        device: DeviceInfo,
        profileType: GamingProfileType,
        comparison: BenchmarkComparison?
    ): Bitmap {
        val bmp = Bitmap.createBitmap(W, H, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bmp)

        // Background gradient — Deep Navy with a cyan glow
        val bgPaint = Paint().apply {
            shader = RadialGradient(
                W / 2f, H * 0.3f, W * 0.9f,
                Color.parseColor("#10182E"), Color.parseColor("#0A0E1F"),
                Shader.TileMode.CLAMP
            )
        }
        canvas.drawRect(0f, 0f, W.toFloat(), H.toFloat(), bgPaint)

        val cyan = Color.parseColor("#00E5FF")
        val gold = Color.parseColor("#FFC94A")
        val white = Color.parseColor("#F5F7FA")
        val gray = Color.parseColor("#AAB3C7")

        fun textPaint(color: Int, size: Float, bold: Boolean = false) = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            this.color = color
            textSize = size
            typeface = Typeface.create(Typeface.DEFAULT, if (bold) Typeface.BOLD else Typeface.NORMAL)
        }

        // Brand header
        canvas.drawText("OBITO BOOST", 60f, 130f, textPaint(cyan, 56f, bold = true))
        canvas.drawText("GAMING PERFORMANCE REPORT", 60f, 175f, textPaint(gray, 22f))

        // Divider
        canvas.drawRect(60f, 210f, W - 60f, 213f, Paint().apply { color = Color.parseColor("#223257") })

        // Device + profile
        canvas.drawText("${device.manufacturer} ${device.model}", 60f, 270f, textPaint(white, 34f, bold = true))
        canvas.drawText("Profile: ${profileType.displayName}", 60f, 315f, textPaint(gold, 26f))
        canvas.drawText("Tier: ${device.performanceTier.displayName}", 60f, 355f, textPaint(gray, 24f))

        // Benchmark section
        var y = 460f
        canvas.drawText("FPS BENCHMARK", 60f, y, textPaint(cyan, 28f, bold = true))
        y += 60f

        if (comparison != null) {
            val beforeAvg = comparison.before.averageFps.valueOrNull()
            val afterAvg = comparison.after.averageFps.valueOrNull()

            canvas.drawText(
                "Before: ${beforeAvg?.let { "%.1f".format(it) } ?: "N/A"} FPS",
                60f, y, textPaint(gray, 30f)
            )
            y += 50f
            canvas.drawText(
                "After: ${afterAvg?.let { "%.1f".format(it) } ?: "N/A"} FPS",
                60f, y, textPaint(white, 34f, bold = true)
            )
            y += 60f

            val delta = comparison.fpsDeltaPercent()
            val deltaText = delta.valueOrNull()?.let { d ->
                val sign = if (d >= 0) "+" else ""
                "$sign${"%.1f".format(d)}% change"
            } ?: "Change not available — insufficient measured data"
            canvas.drawText(deltaText, 60f, y, textPaint(gold, 26f, bold = true))
            y += 70f
        } else {
            canvas.drawText("No benchmark run yet for this session", 60f, y, textPaint(gray, 26f))
            y += 70f
        }

        // Footer / watermark
        canvas.drawText(
            "Generated by OBITO BOOST",
            60f, H - 90f, textPaint(gray, 22f)
        )
        canvas.drawText(
            "obitoboost.app",
            60f, H - 55f, textPaint(Color.parseColor("#6E7A96"), 18f)
        )

        return bmp
    }

    fun shareBitmap(context: Context, bitmap: Bitmap, fileName: String = "obito_boost_result.png") {
        val cacheDir = File(context.cacheDir, "exports").apply { mkdirs() }
        val file = File(cacheDir, fileName)
        FileOutputStream(file).use { out ->
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
        }
        val uri: Uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)

        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "image/png"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(shareIntent, "Share your OBITO BOOST result"))
    }
}
